"""Crear tablas

Revision ID: 630b3913215b
Revises: 
Create Date: 2025-02-12 18:04:10.744220

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '630b3913215b'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('consultorio',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('numero', sa.String(length=20), nullable=False),
    sa.Column('piso', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('medico',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=50), nullable=False),
    sa.Column('apellido', sa.String(length=50), nullable=False),
    sa.Column('especialidad', sa.String(length=50), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('paciente',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=50), nullable=False),
    sa.Column('apellido', sa.String(length=50), nullable=False),
    sa.Column('fecha_nacimiento', sa.Date(), nullable=False),
    sa.Column('email', sa.String(length=100), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_table('cita',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('paciente_id', sa.Integer(), nullable=False),
    sa.Column('medico_id', sa.Integer(), nullable=False),
    sa.Column('consultorio_id', sa.Integer(), nullable=False),
    sa.Column('fecha', sa.Date(), nullable=False),
    sa.Column('hora', sa.Time(), nullable=False),
    sa.ForeignKeyConstraint(['consultorio_id'], ['consultorio.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['medico_id'], ['medico.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['paciente_id'], ['paciente.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('medicos')
    op.drop_table('consultorios')
    op.drop_table('citas')
    with op.batch_alter_table('pacientes', schema=None) as batch_op:
        batch_op.drop_index('email')

    op.drop_table('pacientes')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('pacientes',
    sa.Column('id', mysql.INTEGER(display_width=11), autoincrement=True, nullable=False),
    sa.Column('nombre', mysql.VARCHAR(length=50), nullable=False),
    sa.Column('apellido', mysql.VARCHAR(length=50), nullable=False),
    sa.Column('fecha_nacimiento', sa.DATE(), nullable=False),
    sa.Column('email', mysql.VARCHAR(length=100), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_general_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    with op.batch_alter_table('pacientes', schema=None) as batch_op:
        batch_op.create_index('email', ['email'], unique=True)

    op.create_table('citas',
    sa.Column('id', mysql.INTEGER(display_width=11), autoincrement=True, nullable=False),
    sa.Column('paciente_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False),
    sa.Column('medico_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False),
    sa.Column('consultorio_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False),
    sa.Column('fecha', sa.DATE(), nullable=False),
    sa.Column('hora', mysql.TIME(), nullable=False),
    sa.ForeignKeyConstraint(['consultorio_id'], ['consultorios.id'], name='citas_ibfk_3', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['medico_id'], ['medicos.id'], name='citas_ibfk_2', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['paciente_id'], ['pacientes.id'], name='citas_ibfk_1', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_general_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_table('consultorios',
    sa.Column('id', mysql.INTEGER(display_width=11), autoincrement=True, nullable=False),
    sa.Column('numero', mysql.VARCHAR(length=20), nullable=False),
    sa.Column('piso', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_general_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_table('medicos',
    sa.Column('id', mysql.INTEGER(display_width=11), autoincrement=True, nullable=False),
    sa.Column('nombre', mysql.VARCHAR(length=50), nullable=False),
    sa.Column('apellido', mysql.VARCHAR(length=50), nullable=False),
    sa.Column('especialidad', mysql.VARCHAR(length=50), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_general_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.drop_table('cita')
    op.drop_table('paciente')
    op.drop_table('medico')
    op.drop_table('consultorio')
    # ### end Alembic commands ###
