name: CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Login to DockerHub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Build Docker Image
      run: |
        docker build -t citas-medicas-backend .

    - name: Push Docker Image to DockerHub
      run: |
        docker push yourusername/citas-medicas-backend:latest

  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Deploy to Kubernetes
      uses: Azure/k8s-deploy@v1
      with:
        kubeconfig: ${{ secrets.KUBECONFIG }}
        manifests: |
          k8s/deployment.yaml
          k8s/service.yaml
