name: CI/CD Pipeline

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-backend:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      
      - name: Set up Python 3.9
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: Install dependencies and build backend
        run: |
          python -m venv venv
          source venv/bin/activate
          pip install -r requirements.txt
          # Si tienes un script de pruebas puedes agregarlo aquí
          # python -m pytest tests/

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
        
      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          
      - name: Build and push backend image
        uses: docker/build-push-action@v4
        with:
          push: true
          tags: ${{ secrets.DOCKER_USERNAME }}/CasoPracticoPruebasAutomaticas:latest
          context: . 
          file: ./Dockerfile

  deploy:
    needs: [build-backend]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      
      - name: Start Minikube
        uses: medyagh/setup-minikube@master
        
      - name: Deploy to Kubernetes
        run: |
          # Limpiar deployments y servicios existentes
          kubectl delete deployments,services --all || true
          
          # Desplegar backend
          kubectl apply -f k8s/backend-deployment.yaml
          kubectl apply -f k8s/backend-service.yaml
          
          echo "Waiting for backend to be ready..."
          kubectl wait --for=condition=ready pod -l app=backend --timeout=300s
          
          # Verificar estado final
          echo "Final deployment status:"
          kubectl get all
          
          # Mostrar logs de los pods
          echo "Pod logs:"
          kubectl logs -l app=backend --tail=50
          
          # Mostrar URLs de los servicios
          echo "Service URLs:"
          minikube service list
          
          echo "Deployment completed successfully"
